### ISSUE TITLE
More font options

### ISSUE THREAD

**Issue by HiRoS-neko** [0verEngineer/InlineProblems#16]
Could more options for the font be added, preferably at least the font size?

**Comment by 0verEngineer** [comment]
@HiRoS-neko 

Hey, the font size is kinda tricky because it cannot be bigger than the editor font size and it will also change on the fly if you increase the font size per shortcut.

We could just add settings for custom size, if the setting is active it will not change on editor font change and it will also check that the custom size is not greater than the editor size.

What font options besides the size came to your mind?

**Comment by HiRoS-neko** [comment]
It was just the font size at the moment,
I mainly want to make the font smaller than editor size.
Either a delta or a fixed custom size would work well I think.
