### ISSUE TITLE
Awesome plugin.. a maybe big request but could you integrate, total ts errors?

### ISSUE THREAD

**Issue by Jarrodsz** [0verEngineer/InlineProblems#5]
Awesome plugin.. a maybe big request but could you integrate, total ts errors?

https://github.com/mattpocock/ts-error-translator

I have been looking to make a intellj plugin myself but never build one and no idea where to start.

**Comment by 0verEngineer** [comment]
@Jarrodsz Is something similar available as IntelliJ Platform Plugin? Because the linked one is a VSCode Plugin.

If not then i will not be able to integrate them because i do not want to do error translation.

But if you really want the stuff available in Jetbrains IDEs then this would be a cool plugin to build and you could just base the error translation on the existing work of ts-error-translator (did not see a LICENSE in their repo so check this out first)

If the potential new plugin works correct (completely replaces the error messages) my InlineProblems Plugin would just display the translated messages.

**Comment by 0verEngineer** [comment]
Out of scope
