### ISSUE TITLE
Exception starting up the plugin

### ISSUE THREAD

**Issue by mailsanchu** [0verEngineer/InlineProblems#51]
```
2024-01-18 12:47:21,305 [   3856]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate org.overengineer.inlineproblems.ProjectStartupActivity to ProjectActivity [Plugin: org.OverEngineer.InlineProblems]
com.intellij.diagnostic.PluginException: Migrate org.overengineer.inlineproblems.ProjectStartupActivity to ProjectActivity [Plugin: org.OverEngineer.InlineProblems]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:277)

```

**Comment by mailsanchu** [comment]
![image](https://github.com/0verEngineer/InlineProblems/assets/32928538/cc943599-0c7d-4076-a9e5-31f9fc7c8ed5)

**Comment by mailsanchu** [comment]
Java/SpringBoot project

**Comment by 0verEngineer** [comment]
Thanks, does this happen every time you open the project? Or did you notice any pattern that leads to this problem?

**Comment by mailsanchu** [comment]
I am not sure it causes any issues. May be a warning. I just want to let you know

**Comment by mailsanchu** [comment]
Issue happens during the IDE startup. Not releated to opening/closing the project

**Comment by 0verEngineer** [comment]
It seems like with 2023.3.3 the StartupActivity class is not supported / not working anymore, it was marked as obsolete before, but not as deprecated so i thought i can use it without problems in the near future...

I have commented on an existing question https://intellij-support.jetbrains.com/hc/en-us/community/posts/10694274847762-Alternative-to-StartupManager-runAfterOpened?page=1#community_comment_16467991534226 and i hope for an answer there because the alternative to StartupActivity is ProjectActivity but this can only be used with kotlin.
I tried to add it as a Kotlin class but the plugin does not compile this way, i get the error: `Too many arguments for public constructor InlineProblemProject() defined in org.overengineer.inlineproblems.entities.InlineProblemProject` whatever this means because there is only the constructor generated by Lombok (@AllArgsConstructor)

**Comment by 0verEngineer** [comment]
https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/openapi/startup/StartupActivity.kt This is the obsolete StartupActivity class my plugin uses, it is still not deprecated so it should work and should continue working, to me this looks like a bug in IntelliJ, we have to wait for an answer.

Luckily this only is a problem for users of the unity game engine in Rider.

**Comment by 0verEngineer** [comment]
The warning will not be logged in the release version and the StartupActivity will continue to work as before.
